// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy7EmyEHG4qgZiDu5CmBf7BxPt3BhaIME',
    appId: '1:208943699105:web:938445754c22e9f09bcce0',
    messagingSenderId: '208943699105',
    projectId: 'movieapp-6d64a',
    authDomain: 'movieapp-6d64a.firebaseapp.com',
    storageBucket: 'movieapp-6d64a.appspot.com',
    measurementId: 'G-854HZ7366T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Cp5WF8nCGM33k1kvHelW554XV5Ce0Zk',
    appId: '1:208943699105:android:3fe48835917d4e0b9bcce0',
    messagingSenderId: '208943699105',
    projectId: 'movieapp-6d64a',
    storageBucket: 'movieapp-6d64a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-gAhXZjihtCPMwa34IQ8XX46cXK1zVc',
    appId: '1:208943699105:ios:82319967e9074c8c9bcce0',
    messagingSenderId: '208943699105',
    projectId: 'movieapp-6d64a',
    storageBucket: 'movieapp-6d64a.appspot.com',
    iosBundleId: 'com.example.ticketapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh-gAhXZjihtCPMwa34IQ8XX46cXK1zVc',
    appId: '1:208943699105:ios:2b1bfb34c4883a9f9bcce0',
    messagingSenderId: '208943699105',
    projectId: 'movieapp-6d64a',
    storageBucket: 'movieapp-6d64a.appspot.com',
    iosBundleId: 'com.example.ticketapp.RunnerTests',
  );
}
